#!/usr/bin/env python3
"""
Verify pivot_retest_5min event rows against Databento OHLCV data.

This script replays each event in an events CSV (e.g. results/pivot_retest_5min/events_ALL.csv)
using independent Databento minute bars. It then compares expected values from the CSV to
observed outcomes from replay logic.

Strategy logic mirrors src/pivot_retest_5min.py:
- strong bull: close > previous hour high
- strong bear: close < previous hour low
- pivot retest must occur in first 20 minutes of next hour
- TP2 must not be hit before pivot retest
- then evaluate TP1/TP2 hits in same hour and within 2 hours
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any

import pandas as pd  # type: ignore

try:
    import databento as db  # type: ignore
except Exception as exc:  # pragma: no cover - runtime environment dependent
    db = None
    DB_IMPORT_ERROR = exc
else:
    DB_IMPORT_ERROR = None


BOOL_COLS = ["tp1_hit", "tp2_hit", "tp1_within_2h", "tp2_within_2h"]
EXPECTED_COLUMNS = [
    "datetime",
    "direction",
    "pivot_hit_time",
    "tp1_hit",
    "tp2_hit",
    "tp1_within_2h",
    "tp2_within_2h",
    "distance_pivot_to_tp1",
    "distance_pivot_to_tp2",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Verify pivot_retest_5min events against Databento data."
    )
    parser.add_argument(
        "--events-path",
        default="results/pivot_retest_5min/events_ALL.csv",
        help="Path to event log CSV generated by pivot_retest_5min.py",
    )
    parser.add_argument(
        "--out-path",
        default=None,
        help="Output CSV path for verification report. Default: next to events file.",
    )
    parser.add_argument(
        "--dataset",
        default="GLBX.MDP3",
        help="Databento dataset (default: GLBX.MDP3)",
    )
    parser.add_argument(
        "--symbol",
        default="NQ.c.0",
        help="Databento symbol (default: NQ.c.0)",
    )
    parser.add_argument(
        "--stype-in",
        default="continuous",
        help="Databento stype_in for --symbol (default: continuous)",
    )
    parser.add_argument(
        "--events-tz",
        default="America/Chicago",
        help="Timezone for event datetimes in your CSV (default: America/Chicago)",
    )
    parser.add_argument(
        "--api-key",
        default=None,
        help="Databento API key. If omitted, reads from --api-key-env.",
    )
    parser.add_argument(
        "--api-key-env",
        default="DATABENTO_API_KEY",
        help="Environment variable name for Databento API key.",
    )
    parser.add_argument(
        "--month",
        default=None,
        help='Filter events by YYYY-MM, e.g. "2026-01". Strongly recommended to control cost.',
    )
    parser.add_argument(
        "--start",
        default=None,
        help='Filter event datetime >= this value (event timezone). Example: "2026-01-01".',
    )
    parser.add_argument(
        "--end",
        default=None,
        help='Filter event datetime <= this value (event timezone). Example: "2026-01-31 23:59:59".',
    )
    parser.add_argument(
        "--max-events",
        type=int,
        default=None,
        help="Limit to first N events after filtering.",
    )
    parser.add_argument(
        "--max-range-days",
        type=float,
        default=35.0,
        help="Safety cap for requested Databento range (default: 35 days).",
    )
    parser.add_argument(
        "--allow-large-range",
        action="store_true",
        help="Allow Databento requests larger than --max-range-days.",
    )
    parser.add_argument(
        "--pivot-time-tol-min",
        type=float,
        default=5.0,
        help="Allowed pivot time difference (minutes) for match flag.",
    )
    parser.add_argument(
        "--distance-tol",
        type=float,
        default=0.25,
        help="Allowed absolute distance difference for distance match flags.",
    )
    return parser.parse_args()


def normalize_bool_series(s: pd.Series) -> pd.Series:
    out = s.astype(str).str.strip().str.lower().map({"true": True, "false": False})
    return out


def parse_events(events_path: Path) -> pd.DataFrame:
    if not events_path.exists():
        raise FileNotFoundError(f"Events file not found: {events_path}")

    events = pd.read_csv(events_path)
    missing_cols = [c for c in EXPECTED_COLUMNS if c not in events.columns]
    if missing_cols:
        raise ValueError(f"Events file is missing columns: {missing_cols}")

    events["datetime"] = pd.to_datetime(events["datetime"], errors="coerce")
    events["pivot_hit_time"] = pd.to_datetime(events["pivot_hit_time"], errors="coerce")
    bad_dt = events["datetime"].isna().sum()
    if bad_dt > 0:
        raise ValueError(f"Found {bad_dt} rows with invalid datetime.")

    for col in BOOL_COLS:
        events[col] = normalize_bool_series(events[col])

    events["direction"] = events["direction"].astype(str).str.strip().str.lower()
    bad_direction = ~events["direction"].isin(["bull", "bear"])
    if bad_direction.any():
        raise ValueError(
            f"Found invalid direction values: {sorted(events.loc[bad_direction, 'direction'].unique())}"
        )

    events["distance_pivot_to_tp1"] = pd.to_numeric(
        events["distance_pivot_to_tp1"], errors="coerce"
    )
    events["distance_pivot_to_tp2"] = pd.to_numeric(
        events["distance_pivot_to_tp2"], errors="coerce"
    )
    return events


def apply_filters(events: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    out = events.copy()
    if args.month:
        out = out[out["datetime"].dt.strftime("%Y-%m") == args.month]

    if args.start:
        start_dt = pd.to_datetime(args.start, errors="raise")
        out = out[out["datetime"] >= start_dt]
    if args.end:
        end_dt = pd.to_datetime(args.end, errors="raise")
        out = out[out["datetime"] <= end_dt]

    out = out.sort_values("datetime").reset_index(drop=True)
    if args.max_events is not None:
        out = out.head(args.max_events).copy()
    return out


def event_range_to_utc(events: pd.DataFrame, tz: str) -> tuple[pd.Timestamp, pd.Timestamp]:
    dt = events["datetime"]
    if getattr(dt.dt, "tz", None) is None:
        aware = dt.dt.tz_localize(tz)
    else:
        aware = dt.dt.tz_convert(tz)
    start = (aware.min() - pd.Timedelta(hours=2)).tz_convert("UTC")
    end = (aware.max() + pd.Timedelta(hours=4)).tz_convert("UTC")
    return start, end


def normalize_dbn_df(df_raw: pd.DataFrame, events_tz: str) -> pd.DataFrame:
    df = df_raw.copy()
    if "ts_event" not in df.columns:
        df = df.reset_index()
    if "ts_event" not in df.columns:
        raise ValueError("Could not locate 'ts_event' in Databento dataframe.")

    for col in ["open", "high", "low", "close"]:
        if col not in df.columns:
            raise ValueError(f"Missing expected OHLC column from Databento data: {col}")
        df[col] = pd.to_numeric(df[col], errors="coerce")

    if "volume" in df.columns:
        df["volume"] = pd.to_numeric(df["volume"], errors="coerce").fillna(0.0)
    else:
        df["volume"] = 0.0

    # Some feeds represent prices as fixed-point integers.
    close_abs_med = df["close"].abs().median()
    if pd.notna(close_abs_med) and close_abs_med > 1_000_000:
        for col in ["open", "high", "low", "close"]:
            df[col] = df[col] / 1_000_000_000.0

    ts = pd.to_datetime(df["ts_event"], utc=True, errors="coerce")
    bad_ts = ts.isna().sum()
    if bad_ts > 0:
        raise ValueError(f"Found {bad_ts} rows with invalid Databento timestamps.")

    dt_local = ts.dt.tz_convert(events_tz).dt.tz_localize(None)
    out = (
        df.assign(datetime=dt_local)[["datetime", "open", "high", "low", "close", "volume"]]
        .dropna(subset=["datetime", "open", "high", "low", "close"])
        .sort_values("datetime")
    )
    out = out[~out["datetime"].duplicated(keep="first")]
    out = out.set_index("datetime")
    return out


def ohlcv_agg(df: pd.DataFrame, freq: str) -> pd.DataFrame:
    agg = {
        "open": "first",
        "high": "max",
        "low": "min",
        "close": "last",
        "volume": "sum",
    }
    out = df.resample(freq, label="left", closed="left").agg(agg)
    out = out.dropna(subset=["open", "high", "low", "close"])
    return out


def first_hit_time(level: float, bars: pd.DataFrame) -> pd.Timestamp | None:
    if bars.empty:
        return None
    touched = (bars["low"] <= level) & (level <= bars["high"])
    touched_vals = touched.to_numpy()
    if not touched_vals.any():
        return None
    return bars.index[int(touched_vals.argmax())]


def was_hit(level: float, bars: pd.DataFrame) -> bool:
    if bars.empty:
        return False
    return bool(((bars["low"] <= level) & (level <= bars["high"])).any())


def tsdiff_minutes(a: pd.Timestamp | None, b: pd.Timestamp | None) -> float | None:
    if a is None or b is None:
        return None
    return float(abs((a - b).total_seconds()) / 60.0)


def bool_match(expected: Any, observed: Any) -> bool | None:
    if pd.isna(expected) or observed is None:
        return None
    return bool(expected) == bool(observed)


def distance_match(expected: float, observed: float | None, tol: float) -> bool | None:
    if pd.isna(expected) or observed is None:
        return None
    return abs(float(expected) - float(observed)) <= tol


def _index_surrounding_timestamps(
    idx: pd.DatetimeIndex, target: pd.Timestamp
) -> tuple[pd.Timestamp | None, pd.Timestamp | None]:
    if len(idx) == 0:
        return None, None
    pos = int(idx.searchsorted(target, side="left"))
    before = idx[pos - 1] if pos - 1 >= 0 else None
    after = idx[pos] if pos < len(idx) else None
    return before, after


def _minutes_between(a: pd.Timestamp | None, b: pd.Timestamp | None) -> float | None:
    if a is None or b is None:
        return None
    return float(abs((a - b).total_seconds()) / 60.0)


def verify_events(
    events: pd.DataFrame,
    h: pd.DataFrame,
    m5: pd.DataFrame,
    pivot_time_tol_min: float,
    distance_tol: float,
) -> pd.DataFrame:
    results: list[dict[str, Any]] = []
    eps = pd.Timedelta(microseconds=1)
    h_idx = h.index.sort_values()

    for row in events.itertuples(index=False):
        ts: pd.Timestamp = row.datetime
        direction: str = row.direction
        expected_pivot_time = row.pivot_hit_time if not pd.isna(row.pivot_hit_time) else None

        base: dict[str, Any] = {
            "datetime": ts,
            "direction": direction,
            "expected_pivot_hit_time": expected_pivot_time,
            "expected_tp1_hit": row.tp1_hit,
            "expected_tp2_hit": row.tp2_hit,
            "expected_tp1_within_2h": row.tp1_within_2h,
            "expected_tp2_within_2h": row.tp2_within_2h,
            "expected_distance_pivot_to_tp1": row.distance_pivot_to_tp1,
            "expected_distance_pivot_to_tp2": row.distance_pivot_to_tp2,
        }

        if ts not in h.index:
            before, after = _index_surrounding_timestamps(h_idx, ts)
            results.append(
                {
                    **base,
                    "verification_status": "missing_hourly_bar",
                    "expected_current_hour_ts": ts,
                    "nearest_hour_before_current_ts": before,
                    "nearest_hour_after_current_ts": after,
                    "gap_to_before_current_min": _minutes_between(ts, before),
                    "gap_to_after_current_min": _minutes_between(after, ts),
                    "missing_reason": "No Databento 1h bar at event timestamp (session gap or unavailable data).",
                }
            )
            continue

        prev_ts = ts - pd.Timedelta(hours=1)
        if prev_ts not in h.index:
            before, after = _index_surrounding_timestamps(h_idx, prev_ts)
            results.append(
                {
                    **base,
                    "verification_status": "missing_prev_hourly_bar",
                    "expected_prev_hour_ts": prev_ts,
                    "nearest_hour_before_prev_ts": before,
                    "nearest_hour_after_prev_ts": after,
                    "gap_to_before_prev_min": _minutes_between(prev_ts, before),
                    "gap_to_after_prev_min": _minutes_between(after, prev_ts),
                    "missing_reason": "No Databento 1h bar at ts-1h (usually session/holiday boundary).",
                }
            )
            continue

        hour = h.loc[ts]
        prev = h.loc[prev_ts]

        strong_bull = bool(hour["close"] > prev["high"])
        strong_bear = bool(hour["close"] < prev["low"])
        strong_match = (direction == "bull" and strong_bull) or (direction == "bear" and strong_bear)

        if direction == "bull":
            pivot = float(prev["high"])
            tp1 = float(hour["open"])
            tp2 = float(hour["high"])
        else:
            pivot = float(prev["low"])
            tp1 = float(hour["open"])
            tp2 = float(hour["low"])

        next_hour_start = ts + pd.Timedelta(hours=1)
        next_hour_end = ts + pd.Timedelta(hours=2)
        twoh_end = ts + pd.Timedelta(hours=3)
        first20_end_next = next_hour_start + pd.Timedelta(minutes=20)

        m_first20 = m5.loc[next_hour_start : first20_end_next - eps]
        observed_pivot_time = first_hit_time(pivot, m_first20)
        pivot_found = observed_pivot_time is not None

        tp2_before_pivot = None
        observed_tp1_hit = None
        observed_tp2_hit = None
        observed_tp1_within_2h = None
        observed_tp2_within_2h = None

        if pivot_found:
            m_before_pivot = m5.loc[next_hour_start : observed_pivot_time - eps]  # type: ignore[arg-type]
            tp2_before_pivot = was_hit(tp2, m_before_pivot)

            if not tp2_before_pivot:
                m_after_pivot_hour = m5.loc[observed_pivot_time : next_hour_end - eps]  # type: ignore[arg-type]
                m_after_pivot_2h = m5.loc[observed_pivot_time : twoh_end - eps]  # type: ignore[arg-type]
                observed_tp1_hit = was_hit(tp1, m_after_pivot_hour)
                observed_tp2_hit = was_hit(tp2, m_after_pivot_hour)
                observed_tp1_within_2h = was_hit(tp1, m_after_pivot_2h)
                observed_tp2_within_2h = was_hit(tp2, m_after_pivot_2h)

        observed_dist_tp1 = abs(pivot - tp1)
        observed_dist_tp2 = abs(pivot - tp2)

        pivot_diff_min = tsdiff_minutes(expected_pivot_time, observed_pivot_time)
        match_pivot_time = (
            pivot_diff_min is not None and pivot_diff_min <= pivot_time_tol_min
        )

        match_tp1_hit = bool_match(row.tp1_hit, observed_tp1_hit)
        match_tp2_hit = bool_match(row.tp2_hit, observed_tp2_hit)
        match_tp1_2h = bool_match(row.tp1_within_2h, observed_tp1_within_2h)
        match_tp2_2h = bool_match(row.tp2_within_2h, observed_tp2_within_2h)
        match_dist_tp1 = distance_match(row.distance_pivot_to_tp1, observed_dist_tp1, distance_tol)
        match_dist_tp2 = distance_match(row.distance_pivot_to_tp2, observed_dist_tp2, distance_tol)

        if not strong_match:
            status = "strong_condition_failed"
        elif not pivot_found:
            status = "no_pivot_touch_first20"
        elif tp2_before_pivot:
            status = "tp2_hit_before_pivot"
        else:
            status = "ok"

        all_outcome_match = (
            match_tp1_hit is True
            and match_tp2_hit is True
            and match_tp1_2h is True
            and match_tp2_2h is True
        )
        all_distance_match = match_dist_tp1 is True and match_dist_tp2 is True

        results.append(
            {
                **base,
                "strong_bull_observed": strong_bull,
                "strong_bear_observed": strong_bear,
                "strong_condition_match": strong_match,
                "pivot_observed": pivot,
                "tp1_observed": tp1,
                "tp2_observed": tp2,
                "observed_pivot_hit_time": observed_pivot_time,
                "pivot_time_diff_min": pivot_diff_min,
                "match_pivot_time": match_pivot_time,
                "tp2_before_pivot_observed": tp2_before_pivot,
                "observed_tp1_hit": observed_tp1_hit,
                "observed_tp2_hit": observed_tp2_hit,
                "observed_tp1_within_2h": observed_tp1_within_2h,
                "observed_tp2_within_2h": observed_tp2_within_2h,
                "match_tp1_hit": match_tp1_hit,
                "match_tp2_hit": match_tp2_hit,
                "match_tp1_within_2h": match_tp1_2h,
                "match_tp2_within_2h": match_tp2_2h,
                "observed_distance_pivot_to_tp1": observed_dist_tp1,
                "observed_distance_pivot_to_tp2": observed_dist_tp2,
                "match_distance_pivot_to_tp1": match_dist_tp1,
                "match_distance_pivot_to_tp2": match_dist_tp2,
                "all_outcome_match": all_outcome_match,
                "all_distance_match": all_distance_match,
                "verification_status": status,
            }
        )

    out = pd.DataFrame(results)
    out = out.sort_values(["datetime", "direction"]).reset_index(drop=True)
    return out


def write_missing_prev_hourly_report(report: pd.DataFrame, out_path: Path) -> Path | None:
    missing = report[report["verification_status"] == "missing_prev_hourly_bar"].copy()
    if missing.empty:
        return None

    cols = [
        "datetime",
        "direction",
        "expected_pivot_hit_time",
        "expected_prev_hour_ts",
        "nearest_hour_before_prev_ts",
        "nearest_hour_after_prev_ts",
        "gap_to_before_prev_min",
        "gap_to_after_prev_min",
        "missing_reason",
        "expected_tp1_hit",
        "expected_tp2_hit",
        "expected_tp1_within_2h",
        "expected_tp2_within_2h",
        "expected_distance_pivot_to_tp1",
        "expected_distance_pivot_to_tp2",
    ]
    cols = [c for c in cols if c in missing.columns]
    missing = missing[cols].sort_values(["datetime", "direction"]).reset_index(drop=True)

    missing_path = out_path.with_name("verification_missing_prev_hourly_bar.csv")
    missing.to_csv(missing_path, index=False)
    return missing_path


def print_summary(report: pd.DataFrame, out_path: Path) -> None:
    total = len(report)
    ok = int((report["verification_status"] == "ok").sum()) if "verification_status" in report else 0
    ok_match = int(
        ((report["verification_status"] == "ok") & (report["all_outcome_match"] == True)).sum()  # noqa: E712
    )
    ok_mismatch = int(
        ((report["verification_status"] == "ok") & (report["all_outcome_match"] == False)).sum()  # noqa: E712
    )

    print("\n=== Databento Verification Summary ===")
    print(f"Total event rows checked: {total}")
    print(f"Rows passing strategy filters on Databento: {ok}")
    print(f"Rows with all outcome flags matching: {ok_match}")
    print(f"Rows with at least one outcome mismatch: {ok_mismatch}")

    if "verification_status" in report:
        print("\nStatus counts:")
        print(report["verification_status"].value_counts(dropna=False).to_string())

    mismatches = report[
        (report["verification_status"] == "ok") & (report["all_outcome_match"] == False)  # noqa: E712
    ]
    if not mismatches.empty:
        cols = [
            "datetime",
            "direction",
            "expected_tp1_hit",
            "observed_tp1_hit",
            "expected_tp2_hit",
            "observed_tp2_hit",
            "expected_tp1_within_2h",
            "observed_tp1_within_2h",
            "expected_tp2_within_2h",
            "observed_tp2_within_2h",
        ]
        print("\nSample mismatches (up to 10 rows):")
        print(mismatches[cols].head(10).to_string(index=False))

    print(f"\nSaved report: {out_path}")


def main() -> int:
    args = parse_args()

    if db is None:
        print(
            "Missing dependency: databento\n"
            f"Import error: {DB_IMPORT_ERROR}\n"
            "Install with: pip install databento",
            file=sys.stderr,
        )
        return 2

    api_key = args.api_key or os.getenv(args.api_key_env)
    if not api_key:
        print(
            f"Databento API key is required. Set --api-key or env var {args.api_key_env}.",
            file=sys.stderr,
        )
        return 2

    events_path = Path(args.events_path)
    out_path = Path(args.out_path) if args.out_path else events_path.with_name("verification_databento.csv")

    events = parse_events(events_path)
    events = apply_filters(events, args)
    if events.empty:
        print("No events left after filtering.")
        return 1

    start_utc, end_utc = event_range_to_utc(events, args.events_tz)
    span_days = (end_utc - start_utc).total_seconds() / 86400.0
    if span_days > args.max_range_days and not args.allow_large_range:
        print(
            (
                f"Safety stop: requested Databento range is {span_days:.2f} days, "
                f"which exceeds --max-range-days={args.max_range_days}. "
                "Use --month/--start/--end or pass --allow-large-range."
            ),
            file=sys.stderr,
        )
        return 2

    print("Requesting Databento 1-minute bars...")
    print(f"dataset={args.dataset} symbol={args.symbol} stype_in={args.stype_in}")
    print(f"start_utc={start_utc.isoformat()} end_utc={end_utc.isoformat()}")

    client = db.Historical(api_key)
    dbn = client.timeseries.get_range(
        dataset=args.dataset,
        schema="ohlcv-1m",
        symbols=args.symbol,
        stype_in=args.stype_in,
        start=start_utc.isoformat(),
        end=end_utc.isoformat(),
    )

    raw = dbn.to_df()
    if raw.empty:
        print("Databento returned no rows for the requested range.", file=sys.stderr)
        return 1

    m1 = normalize_dbn_df(raw, args.events_tz)
    m5 = ohlcv_agg(m1, "5min")
    h1 = ohlcv_agg(m1, "1h")

    report = verify_events(
        events=events,
        h=h1,
        m5=m5,
        pivot_time_tol_min=args.pivot_time_tol_min,
        distance_tol=args.distance_tol,
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    report.to_csv(out_path, index=False)
    missing_prev_path = write_missing_prev_hourly_report(report, out_path)
    print_summary(report, out_path)
    if missing_prev_path is not None:
        print(f"Saved missing-prev diagnostics: {missing_prev_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
